project:
  type: website
  output-dir: .

website:
  title: "My Quarto Blog"
  site-url: "https://rvickers-code.github.io"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Posts
        href: posts/


